name: ci pr
# continuous integration on pull requests to main

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  go-lint:
    uses: ./.github/workflows/golangci-lint.yml
  cli-tests:
    uses: ./.github/workflows/clitest.yml
  sol-tests:
    uses: ./.github/workflows/soltest.yml
  e2e-tests:
    uses: ./.github/workflows/pr-e2etest.yml
  vtest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      # TODO(corver): add coverage
      - run: go test -v github.com/omni-network/omni/lib/fireblocks
        env:
          - TESTNET_FIREBLOCKS_API_KEY: ${{ secrets.TESTNET_FIREBLOCKS_API_KEY }}
          - TESTNET_FIREBLOCKS_SECRET: ${{ secrets.TESTNET_FIREBLOCKS_SECRET }}
