name: go tests
# Run this separately from pre-commit for nice visual coverage.

on:
  workflow_call:

jobs:
  unit_tests:
    runs-on: namespace-profile-default
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      # TODO(corver): add coverage
      - run: go test -v github.com/omni-network/omni/lib/fireblocks
